# from https://github.com/grafana/grafana-docker/blob/master/Dockerfile
FROM debian:latest

ARG GRAFANA_VERSION=2.6.0

RUN apt-get update && \
    apt-get -y --no-install-recommends install libfontconfig curl ca-certificates && \
    apt-get clean && \
    curl https://grafanarel.s3.amazonaws.com/builds/grafana_${GRAFANA_VERSION}_amd64.deb > /tmp/grafana.deb && \
    dpkg -i /tmp/grafana.deb && \
    rm /tmp/grafana.deb && \
    curl -L https://github.com/tianon/gosu/releases/download/1.5/gosu-amd64 > /usr/sbin/gosu && \
    chmod +x /usr/sbin/gosu && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

VOLUME ["/var/lib/grafana", "/var/log/grafana", "/etc/grafana"]

EXPOSE 3000

ADD ./conf /etc/grafana/

ADD ./dashboards/ /var/lib/grafana/dashboards/

ADD ./run.sh /run.sh

ENTRYPOINT ["/run.sh"]