version: '2'

services:
  server:
    build: server/.
    ports:
      - "8080:8080"
    environment:
      - http_proxy=http://${PROXY_IP}:3128
      - https_proxy=http://${PROXY_IP}:3128
      - ftp_proxy=http://${PROXY_IP}:3128
      - no_proxy=localhost,127.0.0.1,*.swarm-net
    networks: 
      - swarm-net

  agent:
    build: agent/.
    environment:
      - http_proxy=http://${PROXY_IP}:3128
      - https_proxy=http://${PROXY_IP}:3128
      - ftp_proxy=http://${PROXY_IP}:3128
      - no_proxy=localhost,127.0.0.1,*.swarm-net
    networks: 
      - swarm-net
    
networks:
  swarm-net:
    external: true
