version: '2'

services:

  zookeeper:
    image: jplock/zookeeper
    hostname: zookeeper
    ports: 
      - "2181:2181"
    networks:
      - swarm-net

  influxdb:
    build:
      context: ./influxdb/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    ports:
      - "8083:8083"
      - "8086:8086"
      - "4242:4242"
      - "25826:25826/udp"
    environment:
      - PRE_CREATE_DB=telegraf;collectd;opentsdb;graphite
    networks:
      - swarm-net

  telegraf_influxdb:
    build:
      context: ./telegraf_influxdb/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    hostname: telegraf
    depends_on:
      - influxdb
    networks:
      - swarm-net

  telegraf_kafka:
    build:
      context: ./telegraf_kafka/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    hostname: telegraf
    depends_on:
      - zookeeper
      - kafka
    networks:
      - swarm-net

  collectd_influxdb:
    build:
      context: ./collectd_influxdb/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    ports:
      - "80:80"
    depends_on:
      - influxdb
    networks:
      - swarm-net

  collectd_kafka:
    image: mre0/collectd
    volumes:
     - ./collectd_kafka/collectd.conf:/etc/collectd.conf
    depends_on:
      - kafka
    networks:
      - swarm-net

  chronograf:
    build:
      context: ./chronograf/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    ports:
      - "10000:10000"
    depends_on:
      - influxdb
    networks:
      - swarm-net

  kapacitor:
    build:
      context: ./kapacitor/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    ports:
      - "9092:9092"
    depends_on:
      - influxdb
    networks:
      - swarm-net

  grafana:
    build:
      context: ./grafana/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - swarm-net

  kafka:
    build:
      context: ./kafka/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS=my-topic:1:10,telegraph:1:10,metrics:1:10
    networks:
      - swarm-net

  kafkaclient:
    build:
      context: ./kafka_client/
      args:
        - http_proxy=http://${PROXY_IP}:3128
        - https_proxy=http://${PROXY_IP}:3128
        - ftp_proxy=http://${PROXY_IP}:3128
        - no_proxy=localhost,127.0.0.1
    depends_on:
      - kafka
    networks:
      - swarm-net

networks:
  swarm-net:
    external: true
